export const colors = {
  white: "#FFFFFF",
  whiteIvory: "#FDFFF6",
  whiteSoap: "#FFFAF6",
  beige: "#F6EFE7",
  blackPrimary: "#262626",
  blackMine: "#252424",
  greenOlivine: "#9DB56B",
  greenCucumber: "#81B769",
  greenRock: "#E6E9D3",
  redSunglo: "#E56D6A",
  orange: "#FAA57B",
  orangeNegroni: "#FFE0C9",
  pink: "#FFC5CE",
  blueAnakiwa: "#A6C4FF",
  bluePattens: "#D5E3FF",
  blueSelago: "#E6F1FC",
};
